Repository Scout-NU/thealleyway-site, pull requests merged in 2021-04, with the labels that each got.

#69 Creating colors.js
  style/colors.js
Labels: reusable-component

#71 Updated to Swear Display and Poppins
  style/typography.js
Labels: configuration

#66 Api-Buildout: Update Contact Page
  components/contactConfirmation/ContactConfirmation.js
  pages/contact.js
Labels: api-buildout

#65 Api-Buildout: Update Home Page and Create Featured Stories
  components/featuredStoryPreview/FeaturedStoryPreview.js
  components/newsletterConfirmation/NewsletterConfirmation.js
  lib/api.js
  pages/index.js
Labels: api-buildout

#74 Bug Fix: Safari Clamp Not Responsive
  styles/globals.css
Labels: bug

#78 Setting global body background color
  styles/globals.css
Labels: reusable-component

#77 Initial SVG Upload
  public/assets/double-archway.svg
  public/assets/double-ellipses.svg
  public/assets/filled-back-to-top-arrow.svg
  public/assets/filled-long-arrow.svg
  public/assets/filled-spark-for-popup.svg
  public/assets/filled-spark-white.svg
  public/assets/long-filled-spark-arrow.svg
  public/assets/long-unfilled-spark-arrow.svg
  public/assets/refined-squiggle.svg
  public/assets/short-squiggle.svg
  public/assets/single-archway.svg
  public/assets/spark-exiting-archway.svg
  public/assets/squiggle-underline.svg
  public/assets/squiggle-wavy.svg
  public/assets/unfilled-back-to-top-arrow.svg
  public/assets/unfilled-long-arrow.svg
  public/assets/unfilled-spark-white-outline.svg
  style/icons.js
Labels: reusable-component

#57 Creating the Text Input Field
  components/textInputField/TextInputField.js
  components/textInputField/TextInputField.style.js
Labels: reusable-component

#88 Configuration: Updating Breakpoints and max
  lib/responsive.js
Labels: configuration

#87 Hi-Fi: Story Archive
  components/storyArchivePage/StoryArchivePage.js
  components/storyArchivePage/StoryArchivePage.style.js
  components/storyArchivePage/archivePagination/ArchivePagination.js
  components/storyArchivePage/archivePagination/ArchivePagination.style.js
  components/storyArchivePage/archiveSorting/ArchiveSorting.js
  components/storyArchivePage/archiveSorting/ArchiveSorting.style.js
  components/storyArchivePage/archiveStoryPreview/ArchiveStoryPreview.js
  components/storyArchivePage/archiveStoryPreview/ArchiveStoryPreview.style.js
  lib/api.js
  lib/responsive.js
  package-lock.json
  package.json
  pages/archive/[order]/[page].js
  pages/archive/[page].js
  public/_redirects
  public/assets/filled-short-arrow.svg
  style/icons.js
  style/typography.js
Labels: hi-fi

#97 Hi-Fi: Footer
  components/back-to-start-vertical-button/BackToStartVerticalButton.js
  components/back-to-start-vertical-button/BackToStartVerticalButton.styles.js
  components/box-link/BoxLink.js
  components/box-link/BoxLink.styles.js
  components/contact-page/ContactPage.js
  components/contact-page/ContactPage.styles.js
  components/footer/Footer.js
  components/footer/Footer.style.js
  components/footer/footer-link/FooterLink.js
  components/footer/footer-link/FooterLink.style.js
  components/image-box-link/ImageBoxLink.js
  components/image-box-link/ImageBoxLink.styles.js
  components/navigation/Navigation.js
  components/story-archive-page/StoryArchivePage.js
  components/story-archive-page/archive-story-preview/ArchiveStoryPreview.js
  lib/hooks.js
  pages/about.js
  pages/story-inquiry.js
  styles/globals.css
Labels: hi-fi
